filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'
        - 'app/*'
        - 'bin/*'
        - 'library/*'
    paths: {  }
tools:
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
    php_cpd:
        enabled: true
        excluded_dirs: {  }
        names:
            - '*.php'
        min_lines: 5
        min_tokens: 70
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
    external_code_coverage:
        enabled: true
        timeout: 300
        runs: 1
        filter:
            excluded_paths:
                - 'vendor/*'
                - 'tests/*'
                - 'app/*'
                - 'bin/*'
                - 'library/*'
            paths: {  }
build_failure_conditions: {  }
