<?php
/**
 * Change Password Form View
 * @author Kaushal Kishore(kaushal.rahuljaiswal@gmail.com)
 * 
 */
$form = $this->changePasswordForm;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formElement($form->get('loginCsrf'));
$errorMessage = $this->flashMessenger()->getMessages();
?>
<div class="general-form-container client-profile clearfix float-l">
    <div id="changePasswordPage" class="title" class="form-action text-right"
		style="float: left; width: 100%; padding: 0;">
		<div style="float:left;">
			<h2>Change Password</h2>
		</div>
	</div>
	<?php
    if (count($errorMessage)) :
    $errorMessage = $errorMessage[0];
    ?>
    <div class="server-error cms-error-margin" style="margin-top:50px;">
    <ul>
        <?php foreach ($errorMessage as $type => $msg) : ?>
        <li><span class="<?php echo $type; ?>"><?php echo $msg; ?></span></li>
        <?php endforeach; ?>
    </ul>
    </div>
    <?php endif; ?>
    
	<div class="form-row">
		<div class="field-type1 float-l">
			<label class="form-label-half"><?php echo $this->formlabel($form->get('old_password'));?><span
				class="star">*</span></label>
			<div class="form-fields full-width-half">	   <?php echo $this->formelement($form->get('old_password'));?>
                   <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('old_password'));?></span>
			</div>
		</div>
	</div>
	<div class="form-row">
		<div class="field-type1 float-l">
			<label class="form-label-half"><?php echo $this->formlabel($form->get('new_password'));?><span
				class="star">*</span></label>
			<div class="form-fields full-width-half">	   <?php echo $this->formelement($form->get('new_password'));?>
                   <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('new_password'));?></span>
			</div>
		</div>
	</div>
	<div class="form-row">
		<div class="field-type1 float-l">
			<label class="form-label-half"><?php echo $this->formlabel($form->get('confirm_password'));?><span
				class="star">*</span></label>
			<div class="form-fields full-width-half">	   <?php echo $this->formelement($form->get('confirm_password'));?>
                   <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('confirm_password'));?></span>
			</div>
		</div>
	</div>
	<div class="sign-btn" style="float: left;">
        <?php  echo $this->formRow($form->get('submit'));?>
    </div>

</div>
<?php echo $this->form()->closeTag(); ?>