<?php
/**
 * Forgot Password Form View
 * @author Kaushal Kishore(kaushal.rahuljaiswal@gmail.com)
 * 
 */
$form = $this->forgotPasswordForm;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formElement($form->get('loginCsrf'));
$errorMessage =  $this->flashMessenger()->getMessages();
?>
<h2 class="sign-title">Password Reset</h2>
<div class="login-bottom">
	<div class="general-form-container forgot-password-form clearfix">
	<?php if(count($errorMessage)) : 
            $errorMessage = $errorMessage[0];
            ?>
            <div class="server-error padding-bottom_30">
            <ul>
                <?php foreach ($errorMessage as $type => $msg) : ?>
                <li><span class="<?php echo $type; ?>"><?php echo $msg; ?></span></li>
                <?php endforeach; ?>
            </ul>
            </div>
            <?php endif; ?>
			<div class="form-row">
				<label class="form-label-half">
				    <?php echo $this->formlabel($form->get('userName'));?>
				</label>
				<div class="form-fields full-width-half">
				    <?php echo $this->formelement($form->get('userName'));?>
				    
				</div>
                <div class="msg-note clr float-l">After clicking submit, check your inbox for an email with instructions on how to reset your password.  If you do not receive an email shortly, check your spam folder.</div>
			</div>
			<div class="form-row clearfix">
				<div class="sign-btn" style="padding-right:3px;">
					<?php echo $this->formElement ( $form->get ( 'submit' ) )?>
				</div>
			</div>
	</div>
</div>
