<?php
/**
 * Reset Password Confirmation Form View
 * @author Kaushal Kishore(kaushal.rahuljaiswal@gmail.com)
 * 
 */
$errorMessage =  $this->flashMessenger()->getMessages();
?>
<h2 class="sign-title">Password Reset</h2>
<div class="login-bottom float-l" style="width:99%; margin-bottom:10px;">

	<div class="general-form-container forgot-password-form clearfix">
	<?php if(count($errorMessage)) : 
        $errorMessage = $errorMessage[0];
        ?>
        <div class="server-error padding-bottom_30">
            <ul>
                <?php foreach ($errorMessage as $type => $msg) : ?>
               <li><span class="<?php echo $type; ?>"><?php echo $msg; ?></span></li>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php endif; ?>
			<div class="form-row">
                <div class="msg-note clr float-l" style="font-weight: bold;">
                    You have successfully reset your password.<br>
                    Please proceed to Sign In.
                </div>
			</div>
			<div class="form-row">
                <div class="sign-btn">
                    <input type="button" value="Sing In" class="btn" onClick="window.location='/users'">
                </div>
			</div>
	</div>
</div>
