<?php
/**
 * Reset Password Form View
 * @author Kaushal Kishore(kaushal.rahuljaiswal@gmail.com)
 * 
 */
$form = $this->resetPasswordForm;
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formElement($form->get('loginCsrf'));
$errorMessage =  $this->flashMessenger()->getMessages();

?>
<h2 class="sign-title">You have requested to reset your password</h2>
<div class="login-bottom ">
<?php if(count($errorMessage)) : 
$errorMessage = $errorMessage[0];
?>
<div class="server-error">
    <ul>
        <?php foreach ($errorMessage as $type => $msg) : ?>
       <li><span class="<?php echo $type; ?>"><?php echo $msg; ?></span></li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
	<div class="general-form-container forgot-password-form clearfix">
            <div class="msg-note clr float-l">Please enter your new password below.
             Your password must include at least one capital letter,one small letter,
              one number and one special character.</div>
			<div class="form-row" style="margin-top: 5px;">
				<div class="form-fields full-width-half">
				    <?php echo $this->formelement($form->get('new_password'));?>
				</div>
			</div>
			<div class="form-row">
				<label class="form-label-half"><?php echo $this->formlabel($form->get('confirm_password'));?></label>
				<div class="form-fields full-width-half">
					<?php echo $this->formelement($form->get('confirm_password'));?>
				</div>
			</div>
			<div class="form-row clearfix">
				<div class="sign-btn">
					<?php echo $this->formElement ( $form->get ( 'submit' ) )?>
				</div>
			</div>
	</div>
</div>